version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true

  storage:
    image: redis:7.0-alpine
    ports:
      - '5020:6379'

  decisionhelper.api:
    image: ${DOCKER_REGISTRY-}decisionhelperapi
    depends_on:
      - storage
    build:
      context: .
      dockerfile: src/DecisionHelper.API/Dockerfile
    environment:
      REDIS__HOSTS__0__HOST: storage
      REDIS__HOSTS__0__PORT: 6379