global using Xunit;
global using Moq;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.AspNetCore.TestHost;
global using Microsoft.Extensions.DependencyInjection;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using StackExchange.Redis;
global using StackExchange.Redis.Extensions.Core.Abstractions;